name = "ftops-ui"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]
main = "worker.ts"

[assets]
directory = "./build/client"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
